project:
  type: website
  output-dir: docs
  resources: 
    - "posts/grizzly-bear/grizzly_bear_lesson_plan.pdf"


website:
  title: "gdavidson533.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: projects.qmd
        text: Projects
      - href: fun.qmd
        text: Fun!
      - href: resume.qmd
        text: Resume

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    lightbox: true 



